name: libsemigroups_pybind11_dev

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python>=3.12
  - bs4
  - codespell
  - eigen
  - fmt
  - ipython
  - numpy
  - pip
  - pip-tools
  - pkgconfig
  - pybind11
  - pylint
  - pytest
  - python-graphviz
  - ruff
  - sphinx_rtd_theme
  - sphinx-copybutton
  - sphinx
  - sphinxcontrib-bibtex
  - pip:
      - cpplint
