name: libsemigroups-pybind11-doc

channels:
  - conda-forge
  - anaconda

dependencies:
  - libsemigroups==2.0.0
  - pip
  - sphinx-copybutton==0.5.2
  - sphinxcontrib-bibtex==2.6.2
  - packaging==23.2
  - pkgconfig
  - pybind11==2.11.1
  - pyparsing==3.1.1
  
